In [ ]:
#Importando as bibliotecas
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier
import pycaret
from pycaret.classification import *

In [ ]:
# Adicione a sua base nos arquivos
nomeDaBase = "base.csv"

# Nome da sua variável alvo
variavelAlvo = 'STRKBASE'

# Carrega a base de dados
AVC = pd.read_csv(nomeDaBase)
AVC.shape

(14646, 25)

In [ ]:
AVC

,GEND01,SUPSYS16,SUPDIA16,ATRFIB07,DIABETES,BMI,FHSTK,BEAT14,HEAR01,NERV01,...,NAUSEP07,FATIGP07,RECOGN08,CHSTPN07,LEGWLK07,PALPIP07,CONVER08,LIFTNG09,WHOME09,STRKBASE
0,0,150,78,0,2,34.500000,0,37,0,0,...,0,0,1,0,0,1,1,0,0,0
1,1,116,76,0,1,32.059293,0,40,0,0,...,0,1,1,1,1,0,1,0,0,0
2,0,124,64,0,1,20.000000,1,30,1,0,...,0,1,1,1,0,0,1,0,0,0
3,1,164,82,0,1,23.678376,0,40,1,0,...,0,0,1,0,0,0,1,0,0,0
4,0,156,80,0,3,21.346278,0,32,0,0,...,0,0,1,0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14641,1,137,75,0,1,21.825815,0,31,1,0,...,0,0,1,1,0,0,0,0,0,2
14642,0,133,59,0,2,28.325067,0,24,0,0,...,0,0,1,0,0,0,0,0,0,2
14643,0,162,76,0,1,28.259417,0,21,0,0,...,0,0,1,0,0,0,1,0,0,2
14644,0,127,50,0,1,25.667093,0,30,0,0,...,0,0,1,0,0,0,0,0,0,2
14645,0,146,66,0,2,29.430251,0,36,0,0,...,0,0,1,0,0,0,1,0,0,2

In [ ]:
setup_classificao = setup(data=AVC, target=variavelAlvo, train_size=0.8, n_jobs=1)

                               Description             Value
0                               session_id               484
1                                   Target          STRKBASE
2                              Target Type        Multiclass
3                            Label Encoded              None
4                            Original Data       (14646, 25)
5                           Missing Values             False
6                         Numeric Features                 4
7                     Categorical Features                20
8                         Ordinal Features             False
9                High Cardinality Features             False
10                 High Cardinality Method              None
11                   Transformed Train Set       (11716, 31)
12                    Transformed Test Set        (2930, 31)
13                      Shuffle Train-Test              True
14                     Stratify Train-Test             False
15                          Fold Generator   StratifiedKFold
16                             Fold Number                10
17                                CPU Jobs                 1
18                                 Use GPU             False
19                          Log Experiment             False
20                         Experiment Name  clf-default-name
21                                     USI              9e61
22                         Imputation Type            simple
23          Iterative Imputation Iteration              None
24                         Numeric Imputer              mean
25      Iterative Imputation Numeric Model              None
26                     Categorical Imputer          constant
27  Iterative Imputation Categorical Model              None
28           Unknown Categoricals Handling    least_frequent
29                               Normalize             False
30                        Normalize Method              None
31                          Transformation             False
32                   Transformation Method              None
33                                     PCA             False
34                              PCA Method              None
35                          PCA Components              None
36                     Ignore Low Variance             False
37                     Combine Rare Levels             False
38                    Rare Level Threshold              None
39                         Numeric Binning             False
40                         Remove Outliers             False
41                      Outliers Threshold              None
42                Remove Multicollinearity             False
43             Multicollinearity Threshold              None
44             Remove Perfect Collinearity              True
45                              Clustering             False
46                    Clustering Iteration              None
47                     Polynomial Features             False
48                       Polynomial Degree              None
49                    Trignometry Features             False
50                    Polynomial Threshold              None
51                          Group Features             False
52                       Feature Selection             False
53                Feature Selection Method           classic
54            Features Selection Threshold              None
55                     Feature Interaction             False
56                           Feature Ratio             False
57                   Interaction Threshold              None
58                           Fix Imbalance             False
59                    Fix Imbalance Method             SMOTE

INFO:logs:create_model_container: 0
INFO:logs:master_model_container: 0
INFO:logs:display_container: 1
INFO:logs:Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=True, features_todrop=[],
                                      id_columns=[],
                                      ml_usecase='classification',
                                      numerical_features=[], target='STRKBASE',
                                      time_features=[])),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None,
                                fill_value_numerical=None,
                                numeric_str...
                ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='STRKBASE')),
                ('fix_perfect', Remove_100(target='STRKBASE')),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough')],
         verbose=False)
INFO:logs:setup() succesfully completed......................................

In [ ]:
best = compare_models()

In [ ]:
best

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
                       oob_score=False, random_state=484, verbose=0,
                       warm_start=False)

In [ ]:
evaluate_model(best)

In [ ]:
predict = predict_model(best)
predict

In [ ]:
AVC

,GEND01,SUPSYS16,SUPDIA16,ATRFIB07,DIABETES,BMI,FHSTK,BEAT14,HEAR01,NERV01,...,NAUSEP07,FATIGP07,RECOGN08,CHSTPN07,LEGWLK07,PALPIP07,CONVER08,LIFTNG09,WHOME09,STRKBASE
0,0,150,78,0,2,34.500000,0,37,0,0,...,0,0,1,0,0,1,1,0,0,0
1,1,116,76,0,1,32.059293,0,40,0,0,...,0,1,1,1,1,0,1,0,0,0
2,0,124,64,0,1,20.000000,1,30,1,0,...,0,1,1,1,0,0,1,0,0,0
3,1,164,82,0,1,23.678376,0,40,1,0,...,0,0,1,0,0,0,1,0,0,0
4,0,156,80,0,3,21.346278,0,32,0,0,...,0,0,1,0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14641,1,137,75,0,1,21.825815,0,31,1,0,...,0,0,1,1,0,0,0,0,0,2
14642,0,133,59,0,2,28.325067,0,24,0,0,...,0,0,1,0,0,0,0,0,0,2
14643,0,162,76,0,1,28.259417,0,21,0,0,...,0,0,1,0,0,0,1,0,0,2
14644,0,127,50,0,1,25.667093,0,30,0,0,...,0,0,1,0,0,0,0,0,0,2
14645,0,146,66,0,2,29.430251,0,36,0,0,...,0,0,1,0,0,0,1,0,0,2